set -g default-terminal "screen-256color"

##################
### Status Bar ###
##################

# Style for the currently active window
set -g window-status-current-style fg=black,bg=blue,bold

# Format for the currently active window
set -g window-status-current-format " #I:#W "


# Set the time tmux waits before giving control back to whatever process is running inside it.
# Otherwise <ESC> in vim has a noticeable delay
set -sg escape-time 10

# Split vertically
unbind %
bind | split-window -h

# Split horizontally
unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

# Unbind and rebind x so that you don't have to confirm it
unbind x
bind-key x kill-pane

# Resize panes by direction
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5


# Toggle max/min the current pane
bind -r m resize-pane -Z

# Allow mouse control
set -g mouse on

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
